### ISSUE TITLE
程序的输出没办法被重定向到tmpfs

### ISSUE THREAD

**Issue by virusdefender** [quark-zju/lrun#21]
我想把程序的输出重定向到tmpfs里面，减少磁盘io，但是发现程序运行结束之后tmpfs中的文件还在。

```
lrun  --tmpfs /usr/ 240 sh s.sh 3>&2
```
s.sh是
```
touch /usr/1.txt
ls /usr
```
输出的是1.txt，然后`ls /usr`的时候就没有1.txt了。
这个是符合预期的。

但是如果使用
```
lrun -tmpfs /usr/ 240 /var/judge/a.out 1>/usr/1.out 3>&2
```
a.out是一个c程序，可以任意的printf一些内容。

但是程序运行结束后，发现/usr/1.out还是存在的呢。

请教一下这个是我的问题，还是lrun的问题。谢谢~

**Comment by quark-zju** [comment]
由 lrun 启动的程序有独立的文件系统挂载点， 你使用 `--tmpfs` 指定的临时目录在程序退出后会被销毁。

如果你使用 `lrun --tmpfs /usr 240 bash` 然后可以在这个 bash 中运行 s.sh 并且观察到 /usr/1.txt，但从外界是访问不到的，该 bash 退出后也就无法再访问到。

**Comment by virusdefender** [comment]
额 不不不~你误解了我的意思

我知道你说的，也应该是这样的。但是我在将程序的输出重定向的时候，在进程结束后文件却还是存在的。

你可以再看下我上面说的。

谢谢~

**Comment by quark-zju** [comment]
这是因为在 `lrun -tmpfs /usr/ 240 /var/judge/a.out 1>/usr/1.out 3>&2` 在这条命令里，`1>/usr/1.out` 这一部分是当前 shell，也就是即将执行 lrun 的 shell 处理的，它看到的是未隔离的文件系统。

**Comment by virusdefender** [comment]
明白了~我觉得也是这个原因 

再次感谢
