### ISSUE TITLE
Vagrant Issue

### ISSUE THREAD

**Issue by hjspku** [quark-zju/lrun#22]
always get an output like:

`install -D -m4550 -oroot -glrun lrun /usr/local/bin/lrun`

and couldn't get any output through 

`sudo lrun --uid 1000 --gid 1000 --max-cpu-time 1.5 bash -c ':(){ :;};:' 3>&1`

and if without sudo, will get `-bash: /usr/local/bin/lrun: Permission denied`

are these all expected?

**Comment by quark-zju** [comment]
The first one is unexpected. What's the output of `sudo lrun --debug --uid 1000 --gid 1000 --max-cpu-time 1.5 bash -c ':(){ :;};:' 3>&1` ?

The second is possibly expected. You may forget to make the current user a member of `lrun` group or relogin the user.

**Comment by quark-zju** [comment]
Oh, the first one is also expected indeed. It seems `sudo` or the shell have some tricky behavior, making lrun believe that fd 3 is not writeable. You can try this command instead:

```
sudo bash -c "lrun --uid 1000 --gid 1000 --max-cpu-time 1.5 bash -c ':(){ :;};:' 3>&1"
```

**Comment by quark-zju** [comment]
I think I can close it now. Free free to re-open if you have any question.
