### ISSUE TITLE
How to properly uninstall lrun?

### ISSUE THREAD

**Issue by wangtz0607** [quark-zju/lrun#34]
I have already built lrun from source and installed it on my machine. It works fine. Now I'm considering whether there is a way to properly uninstall lrun. I have no idea what I should do to uninstall because it's hard for me to figure out what the installation script done to the system, and how to undo these changes.

**Comment by quark-zju** [comment]
Sorry for the late reply. Depending on how you install lrun. If you used `.deb` (Debian or Ubuntu) or `AUR` (Archlinux), then the system package manager can uninstall lrun cleanly.

If you install from source (by using `rake install`) then running:

     sudo groupdel lrun
     sudo rm $(which lrun)

would be enough to uninstall.
