### ISSUE TITLE
如何根据lrun输出的结果得出是否触发了禁用的syscall

### ISSUE THREAD

**Issue by Poisson1204** [quark-zju/lrun#38]

**Comment by quark-zju** [comment]
目前来说没有办法

**Comment by Poisson1204** [comment]
目前lrun的策略是忽略危险的syscall(不执行)，不会直接杀死进程是吗？

**Comment by quark-zju** [comment]
默认不对 syscall 做过滤，ljudge 默认使用 lrun 禁用网络，使用只读文件系统和单独的 pid namespace，所以即便不过滤 syscall 也不会有什么问题。如果使用 seccomp filter 则可以指定 syscall 行为，具体是杀死进程，还是返回错误可配置，是 libseccomp 提供的功能。

**Comment by Poisson1204** [comment]
非常感谢！！！
